### ISSUE TITLE
Prototype frontend design

### ISSUE THREAD

**Issue by zarino** [everypolitician/gender-crowdsourcing#1]
* Four buttons: male, female, other, skip
* All MPs will have a name, some will have a photo too
* Navigation leading to:
   * country selection (users select a country first, before starting)
   * level selection (levels = parliamentary terms, you work backwards from present)
* Mobile-first

**Comment by zarino** [comment]
Current thinking is something quick and satisfying, along the lines of (dare I say it) Tinder:

![2-hb_kyl2bppz7gbnwobds6mhuvpfno8hlcoslwh0wr8yqxk](https://cloud.githubusercontent.com/assets/739624/8359021/b0632e74-1b5b-11e5-9bd0-6e3880a7dadf.jpg)

![2qpbixruyjrglnta_bgyapb-sm8peprpnh8illpdkgd9wmys](https://cloud.githubusercontent.com/assets/739624/8359042/d092f292-1b5b-11e5-99ba-781e9125d62b.jpg)

![_clwjr8ebkcka6qbj9hk-mrm_y4w5ngaaagpl6tn2jbdrsye](https://cloud.githubusercontent.com/assets/739624/8359024/b5a272a0-1b5b-11e5-9d22-45cdec2f5486.jpg)

**Comment by zarino** [comment]
Pull request: https://github.com/everypolitician/gender-crowdsourcing/pull/8

![flick](https://cloud.githubusercontent.com/assets/739624/8411855/0e93af08-1e7e-11e5-8245-1eca57f9bc76.gif)

**Comment by wrightmartin** [comment]
It's great, but the action that happens with the the swipe isn't obvious, maybe as you begin the drag to either direction all the buttons go to an 'inactive' state, except for the corresponding one?

How about showing some prompt when you are in the first stages of the swipe ('picked the card up' but not yet taken it in a direction)

Finally, how about a gesture for skipping - swipe up to skip? It should allow you to maintain the lovely flow without needing to click the buttons
