### ISSUE TITLE
Fix flash messages

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-crowdsourcing#12]
Currently the text isn't appearing in them for some reason, there's just a colored box:

![screen shot 2015-07-02 at 11 15 34](https://cloud.githubusercontent.com/assets/22996/8474913/c3add902-20ab-11e5-9712-10bf196e21fe.png)

**Comment by zarino** [comment]
Also, on narrow screens, the messages appear *behind* the header bar:

![screen shot 2015-07-09 at 11 34 18](https://cloud.githubusercontent.com/assets/739624/8593332/942ea034-262e-11e5-8227-0d9a65a998f7.png)

**Comment by zarino** [comment]
Pull request: https://github.com/everypolitician/gender-crowdsourcing/pull/37
