### ISSUE TITLE
Add more social login options

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-crowdsourcing#2]
Currently users can login with Twitter. We should offer other networks as well.

Probably some/all of the following:

- [x] Facebook
- [x] GitHub?
- [x] Google (Plus)?
- [x] LinkedIn

**Comment by tmtmtmtm** [comment]
If we're going to have multiple options, I'd probably add LinkedIn as well, as it hits another demographic. Surely someone has built something that wraps a bunch of these up into a nice interface already though?

**Comment by chrismytton** [comment]
@tmtmtmtm I've added LinkedIn to the list. Adding new logins is trivial thanks to [OmniAuth](https://github.com/intridea/omniauth), e.g. Facebook logins in 25 lines (mostly `Gemfile.lock` changes!) - https://github.com/everypolitician/gender-crowdsourcing/commit/430e4460723c1636c3b5ae79bbd6b80ba3d9fde6.

**Comment by tmtmtmtm** [comment]
Yeah. I meant a nice interface for the front end, though, that offers a gazillion options but in a neatly packaged way with the main ones up front and some clever way to get to the more obscure ones.

**Comment by chrismytton** [comment]
Oh right, I can't recall seeing anything on other sites. They're usually just a list of all the login options with equal weighting. Perhaps @zarino knows of something?

**Comment by chrismytton** [comment]
This is now done, pull request here - https://github.com/everypolitician/gender-crowdsourcing/pull/4

**Comment by zarino** [comment]
@chrismytton As long as there's a vertical or horizontal stack of nice big buttons, and each one's in the site's brand colour, people will understand what they're for.

Eg: the old Pinterest login screen

![7ethr](https://cloud.githubusercontent.com/assets/739624/8375305/f5ca7308-1bf3-11e5-96d0-97c8db3e0bd9.png)

It can get a bit messy when there are more than two options, but this isn't bad:

![screen shot 2015-06-26 at 11 11 11](https://cloud.githubusercontent.com/assets/739624/8375330/24824b94-1bf4-11e5-8f28-51b2af2d6407.png)

Nor is this:

![screen-shot-2015-03-06-at-8 15 00-am](https://cloud.githubusercontent.com/assets/739624/8375333/2bc74a30-1bf4-11e5-8224-419493cbf598.png)

Having a clear separation between the social buttons, and the standard login form, is good. Either with a physical line, or a clear "or" subheading, eg:

![21](https://cloud.githubusercontent.com/assets/739624/8375434/ffb35de8-1bf4-11e5-93f8-bfe71309bf5c.jpg)

![social-login-example](https://cloud.githubusercontent.com/assets/739624/8375440/06722420-1bf5-11e5-8e3f-71972f6094e5.png)

![10df673607e43eb2a18b6f30d9f76603](https://cloud.githubusercontent.com/assets/739624/8375450/1b661a26-1bf5-11e5-95dd-c7fdc5e9dcf5.jpg)
