### ISSUE TITLE
Don't refer to prior terms when there are none

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-crowdsourcing#22]
The "Complete your first term to unlock terms further in the past" should only be shown when there *are* terms further in the past.

**Comment by zarino** [comment]
Eg here, twice:

![screen shot 2015-07-09 at 11 41 19](https://cloud.githubusercontent.com/assets/739624/8593426/8443f95c-262f-11e5-85ad-1e71036f4f5e.png)
