### ISSUE TITLE
Is it just me, or is the link to a country broken?

### ISSUE THREAD

**Issue by zarino** [everypolitician/gender-crowdsourcing#23]
![app](https://cloud.githubusercontent.com/assets/739624/8593399/447ac10c-262f-11e5-9728-a0c5eadff68c.gif)

The country cards lead to https://gender-crowdsourcing.herokuapp.com/country which 404s.

**Comment by stevenday** [comment]
Same for me, but it's only the "recent countries" link that 404s, some of the others work ok, some give a 500

**Comment by zarino** [comment]
Ah, yes, I think this is something that #11 will fix.
