### ISSUE TITLE
Internal Server Error Popup

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-crowdsourcing#26]
It's a little startling for an internal error to trigger a popup:

![screen shot 2015-07-09 at 11 42 33](https://cloud.githubusercontent.com/assets/57483/8593444/a935fcf6-262f-11e5-929b-53a5ccdcd080.png)

**Comment by chrismytton** [comment]
The error I'm seeing in the logs is:

```
2015-07-09T10:46:24.225402+00:00 app[web.1]: FATAL:  terminating connection due to administrator command
2015-07-09T10:46:24.226194+00:00 app[web.1]: 2015-07-09 10:46:24 - Sequel::DatabaseDisconnectError - PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly
```

Which [this SO answer](http://stackoverflow.com/a/27127603) suggests is because we're using the hobby plan.

**Comment by tmtmtmtm** [comment]
Now getting:

![screen shot 2015-07-09 at 12 20 25](https://cloud.githubusercontent.com/assets/57483/8594017/06390a24-2635-11e5-9a12-ceb6099ca615.png)

**Comment by chrismytton** [comment]
Hopefully fixed in https://github.com/everypolitician/gender-crowdsourcing/commit/0d153bf9f1a876e2867f178a8e6d5c2fe56c7966. Please reopen if this appears again.
