### ISSUE TITLE
Model for storing responses

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-crowdsourcing#3]
We need to store the result of what people think when they click male/female/other.

Suggested schema:

- `id`
- `user_id`
- `country_code`
- `legislature_slug`
- `legislative_period_id`
- `gender`

With appropriate validations on the `gender` to ensure it's either `male`, `female` or `other`.

**Comment by tmtmtmtm** [comment]
I'm assuming the first `id` there is the politician-ID? If so, that should be unique per legislature, so you may not need to store the legislative_period_id too, unless you're doing that just to make some queries easier/quicker.

You probably also need to store that the user has skipped someone too, so as to not keep showing them again.

Adding a timestamp is generally a good idea too, especially if we want to show time-delimited league tables (X in the last 7 days)

**Comment by chrismytton** [comment]
I probably don't *need* to store the `legislative_period_id`, but it's one of those things I can imagine myself needing in the future if I don't add it! So I'll probably just leave it in there.

Good points about noting that a user has skipped and adding timestamps.

Regarding skipping, instead of having a `gender` column I've gone with a `choice` column which can be set to `male`, `female`, `other` or `skip`. This means when choosing which politician to show we can simply select from one that the user has never made a choice on.
