### ISSUE TITLE
Remove text labels on back buttons

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-crowdsourcing#31]
It seems like "< Terms" is going to take you to a Terms & Conditions type page, rather than back to the homepage for the country.

**Comment by zarino** [comment]
Maybe it should be the country name?

**Comment by zarino** [comment]
Or, even better, maybe a back arrow without any text, since space in that header is going to be at a premium if the app name is longer than 12 characters.

**Comment by tmtmtmtm** [comment]
:+1: for just a back arrow. I don't think there's any need for the country name.

**Comment by zarino** [comment]
Ok, I've renamed the ticket. We have a similar issue on the country page, where the back link is titled "< Countries", and on a 320px wide screen, that's a very tight fit.

Removing the text label for the button should be a simple way to avoid both issues. Obviously the back button in the browser will also work too.

**Comment by zarino** [comment]
Pull request here: https://github.com/everypolitician/gender-crowdsourcing/pull/44
