### ISSUE TITLE
Remove alert popups

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-crowdsourcing#32]
Rather than using an `alert` popup, show the user a friendly error if there was a problem saving their response to the server.

**Comment by zarino** [comment]
@chrismytton Why tell them at all? Is there anything they can do about it?

**Comment by chrismytton** [comment]
@zarino Yep, fair point. I guess if there's an error saving then we can just show that politician to the user again in the future.

**Comment by zarino** [comment]
> just show that politician to the user again in the future

:+1:
