### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by MyfanwyNixon** [everypolitician/gender-crowdsourcing#35]
If you start on a term, and get through about ten, you suddenly start worrying that it'll take all day. The one I did definitely took longer than I was expecting. I'd like to see a clear indicator, as i go through, of how many there are left to do.

**Comment by tmtmtmtm** [comment]
:+1: And probably also worth making it super-clear that you can stop and come back any time and pick up where you left off.

**Comment by chrismytton** [comment]
Related to #13

**Comment by tmtmtmtm** [comment]
What still needs done on this? Just the explanation of being able to stop & restart? If so I'd suggest reticketing that (possibly as an addition to the onboarding game?), and closing this, as I think #68 fixed the core issue.

**Comment by chrismytton** [comment]
> Just the explanation of being able to stop & restart?

Yep, will open a separate ticket for that.
