### ISSUE TITLE
Pay-off at the end

### ISSUE THREAD

**Issue by MyfanwyNixon** [everypolitician/gender-crowdsourcing#36]
Nothing happens when I've sorted all my reps. I would like a nice pie chart or something equally graphic, plus some Facebook and Twitter buttons so i can tell the whole world what I just did.

But if not that, then some clear indicator of the next step I should take.

**Comment by zarino** [comment]
Yes!

Not only that, I wanted some sort of pay-off *as I'm playing*, like, every now and then, an unobtrusive pop-up at the top of the screen saying a random phrase like "You’re doing great, only 20 left to go!" or whatever.

**Comment by MyfanwyNixon** [comment]
@Zarino - yes, see #35!

**Comment by garethrees** [comment]
+1 on this – I found it a bit weird that the cards disappear but the buttons are still there. Kinda feels like something just broke.

**Comment by garethrees** [comment]
I notice once you re-visit the legislature you've just categorised, you get the message:

> All done! There are no more people to classify for National Assembly for Wales Fourth Assembly

Could display that at a minimum.

I also think it should be more personal – "You have classified all the people in National Assembly for Wales Fourth Assembly". I assume that a different account can still classify this legislature?

**Comment by zarino** [comment]
I wonder whether this is an opportunity for some social boasting? So a message saying "You're all done" or whatever, and then two calls to action – "Tweet your friends" (or similar) and "Keep playing" (which will show the other terms for this country, or, if there are no more terms, show other countries).

**Comment by MyfanwyNixon** [comment]
The number one pay-off I'd like would be to actually see the male/female split at the end. 
The dream pay-off would be for it to be displayed against an average for every country categorised that far.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon you mean based on _your_ categorisations? Or including other people's?

**Comment by MyfanwyNixon** [comment]
Other people's, I guess.

**Comment by tmtmtmtm** [comment]
At this point we're not doing any processing of the incoming information (working out exactly what to do with it, and how, is something we can do post-launch) so I'm a little concerned with showing people data that we haven't done _any_ sanity checking at all on. Showing them their own tallies is probably OK, and might be a useful first step towards #30, but I'm not so sure about showing them anyone else's.
