### ISSUE TITLE
Card overlap

### ISSUE THREAD

**Issue by garethrees** [everypolitician/gender-crowdsourcing#59]
https://gender-crowdsourcing.herokuapp.com/countries/Libya/legislatures/House-of-Representatives/periods/1/person

Ali Khalifa Al'aisawi

![screen shot 2015-07-15 at 11 44 23](https://cloud.githubusercontent.com/assets/282788/8696755/035cfb60-2ae7-11e5-9fdd-f89060f24252.png)

**Comment by garethrees** [comment]
Looks like its just when the next card is taller than the current

![screen shot 2015-07-15 at 11 46 38](https://cloud.githubusercontent.com/assets/282788/8696768/2e85a4a4-2ae7-11e5-8f13-266faae31739.png)

**Comment by tmtmtmtm** [comment]
The needlessly long name that triggered this has now been corrected. There's presumably still a wider design issue here, though.

**Comment by zarino** [comment]
Yeah, I knew this would happen. When I saw it in prototyping, I didn't really mind too much. Do you find it distracting @tmtmtmtm @garethrees? If so, I guess we could relatively easily define a maximum height for the cards.

**Comment by garethrees** [comment]
The first one was pretty distracting and weird. I think a max-height for the card behind the current would be sensible.

**Comment by tmtmtmtm** [comment]
The first one was a very odd case that shouldn't happen very often. Perhaps we could truncate the length of the name on the non-visible card, and then make it fully expand when it's at the front?
