### ISSUE TITLE
you need to be able to select the text of someone's name

### ISSUE THREAD

**Issue by mhl** [everypolitician/gender-crowdsourcing#60]
On seeing the first card, I wanted to copy and paste the person's name into a search engine to find a picture or biography of them. However, clicking and dragging didn't select the text but instead dragged the card to the left and recorded a decision that they were a particular gender.

I think it's important for the data quality that we make it easy for people to find more about the politician rather than making a superficial assertion about their gender from the name; being able to copy and paste the name would be a good start.

**Comment by zarino** [comment]
How about, instead of copying and pasting the name, just giving them a button to "Google it"?

**Comment by tmtmtmtm** [comment]
Ooh, that sounds nice to me. It's also a consistent reminder that that's the behaviour we want, rather than guessing.

**Comment by lizconlan** [comment]
:+1: for the "Google It" button - a couple of times I've caught myself playing a sub game of "which party is this one from" or "what part of the country do they represent"

**Comment by zarino** [comment]
@tmtmtmtm @lizconlan – if we pre-populate a search query, what should it contain? Some combination of person name, country name, and party name? Or just person and country?

**Comment by tmtmtmtm** [comment]
person and country is probably enough, I would think. If that's not enough the person can always refine the search themselves…

**Comment by lizconlan** [comment]
@zarino person and country? for the UK I'm searching manually for e.g. "Royston Smith MP" (I correctly guessed the party there) but I don't think that will hold worldwide
