### ISSUE TITLE
Don't say "Welcome back" if it's the first time a user has logged in

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-crowdsourcing#62]
It welcomes me back:
![screen shot 2015-07-15 at 12 29 05](https://cloud.githubusercontent.com/assets/57483/8697472/245822a8-2aed-11e5-8e2f-0727e03aa7cc.png)

But then gives me a list of everywhere, all at 0%:
![screen shot 2015-07-15 at 12 29 25](https://cloud.githubusercontent.com/assets/57483/8697473/25474b9e-2aed-11e5-88f2-b7ecf47143c8.png)

**Comment by chrismytton** [comment]
This certainly shouldn't be the case as recent countries are calculated directly from the database, and aren't related to sessions. Is it possible that you've logged in with two different social networks and the recent countries are on the one that you're not logged in with in this screen shot?

**Comment by tmtmtmtm** [comment]
If I log in with a different social network, does it know that I'm the same person? If so, I'd expect it not care which account I logged in on, and for my progress to be for *me*, not related to how I logged in. If not, then I wouldn't expect a "Welcome back" and "Continue" at the start…

**Comment by chrismytton** [comment]
No, there's currently no way we can reliably connect different social networks to the same person. So as you say, the issue here is that it's saying "Welcome back" but it should instead be saying something along the lines of "Welcome, first time user, here's the onboarding process…".

**Comment by chrismytton** [comment]
I've updated the title of the issue to make it clear that this is a wording issue.

**Comment by tmtmtmtm** [comment]
Hmmm. That's a definite downside of the 'gazillions of social media login buttons' approach, then. Is it that we can _never_ match people up, or just that we can't _always_ do it? (Or is there a risk of false positives?) If it's just that sometimes we'll miss that it's the same person, but could be right _some_ of time, then it's possibly worth connecting them up (especially if that's fairly simple). 

But yes, just fixing this text is the more important half of that!

**Comment by chrismytton** [comment]
The only piece of information that we get back from every provider is the "name", so there's certainly a risk of false positives. If we could get an email address back from every provider that we could use that to link accounts together but sadly Twitter (and possibly others) don't provide that information.

**Comment by zarino** [comment]
The actual nub of this issue (that completely new users are being told to "continue" rather than "start") is partially fixed by https://github.com/everypolitician/gender-crowdsourcing/pull/66, where new users are shown "Take a dry run" (which leads to the onboarding game) and then, after that, they're taken to the `/countries` list. At any point after that, if they come to the homepage, I think "Continue" makes sense as a verb, because they will have done *something*.
