### ISSUE TITLE
Progress bar hidden by background card

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-crowdsourcing#75]
![screen shot 2015-07-16 at 12 10 38](https://cloud.githubusercontent.com/assets/57483/8721755/86759790-2bb5-11e5-8bae-85521874f643.png)

**Comment by zarino** [comment]
Progress bar was moved up above the cards in https://github.com/everypolitician/gender-crowdsourcing/commit/27d63aa420074fd355adbf91f90e4a08fd927dc9
