### ISSUE TITLE
Better intro text on the landing page

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-crowdsourcing#79]
> Ready to help us categorise the world’s politicians?

![screen shot 2015-07-16 at 13 22 31](https://cloud.githubusercontent.com/assets/22996/8722554/b1c8d044-2bbd-11e5-940e-c2818f4a00da.png)

Currently the page always says "Ready to help us categorise the world’s politicians?", whether you've just logged in for the first time or if you've already played. There is also concern that the word "categorise" might not be quite right.

- [ ] Sentence for new users who have just logged in
- [ ] Sentence for people that have played the game in the past

**Comment by tmtmtmtm** [comment]
Suggestions from @MyfanwyNixon would be much appreciated here!

**Comment by MyfanwyNixon** [comment]
Sentence for new users who have just logged in: (presumably then it also won't say 'welcome back' or 'continue game'?)
> Let's sort the women from the boys.

Sentence for people that have played the game in the past:
> Let's return to the count.

**Comment by tmtmtmtm** [comment]
> Let's sort the women from the boys

Oh, I like that one.

> Let's return to the count

I'd probably have liked this one more if I'd read it before the first one :)  I've no objections to it, but it feels like we might be able to get something better still.

**Comment by tmtmtmtm** [comment]
(I'm also open to us having a bank of different messages for each, and showing a random one each time…)

**Comment by MyfanwyNixon** [comment]
Ha yes, the second one is harder. 

> Let's quantify the patriarchy some more
(a bit off-message, I know)

> Let's assign some more genders
(perhaps a bit dodgy?)

**Comment by tmtmtmtm** [comment]
We also have the 'categorise' issue in the Onboarding:

![screen shot 2015-07-16 at 14 24 07](https://cloud.githubusercontent.com/assets/57483/8723536/6389ec52-2bc6-11e5-87a7-2de8a45b1d69.png)

**Comment by MyfanwyNixon** [comment]
It's possible we're worrying too much - categorise seems to describe the action quite well.
'Label' is another option?

**Comment by tmtmtmtm** [comment]
After further discussion tweaked this one to just "Press the relevant button for each." (https://github.com/everypolitician/gender-crowdsourcing/commit/3035db92a1619bad19d199f97adc55d5893e7405)

**Comment by tmtmtmtm** [comment]
Actually, I think "Let's sort the women from the boys" is good enough to use for both scenarios (new users and returning), rather than needing separate messages…

**Comment by MyfanwyNixon** [comment]
:+1: ok by me
