### ISSUE TITLE
“Take a dry run?”

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-crowdsourcing#82]
![screen shot 2015-07-16 at 13 55 08](https://cloud.githubusercontent.com/assets/57483/8723050/969ec562-2bc2-11e5-8c38-46ffcc9b92c8.png)

This may be a little too idiomatic for non-native English speakers.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon ?

**Comment by MyfanwyNixon** [comment]
Is this to try it out in a way that won't register your results? If so, maybe:
> Try a practice run

**Comment by tmtmtmtm** [comment]
No, it's to play the onboarding game: http://www.gender-balance.org/onboarding

**Comment by MyfanwyNixon** [comment]
I love those faces.

OK well that's usually called 'Take the tutorial' isn't it? Or if that seems a bit off-putting, we could try a simple message like "Here's how".

**Comment by tmtmtmtm** [comment]
Yep, "Here's how" works well!
