### ISSUE TITLE
How to display images?

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-crowdsourcing#9]
Is there a plan for how to actually show the images of politicians? I'm presuming that hot-linking the official sites isn't really the way to go…

**Comment by chrismytton** [comment]
In the interests of doing the simplest thing possible I think just deploying a copy of https://github.com/jpmckinney/image-proxy to heroku and using that to proxy the images on the official site seems like the simplest thing to do. It means that we get caching and it will work over https. There might be something smarter we can do in the longer term, but this is a good start.

**Comment by tmtmtmtm** [comment]
Sounds good.

I'm guessing you'd also like a suitable field in the CSVs? Or are you picking them up from the JSON?

**Comment by chrismytton** [comment]
@tmtmtmtm Yep a field in the CSV would be very useful! It's currently just displaying the placeholder images from the designs.

**Comment by tmtmtmtm** [comment]
I've added this conceptually, though I still need to rebuild the CSV files to include them. https://raw.githubusercontent.com/everypolitician/everypolitician-data/c585d0c/data/Namibia/Council/term-4.csv is a usable testcase in the meantime.

**Comment by chrismytton** [comment]
Image proxy setup on heroku here - https://everypolitician-image-proxy.herokuapp.com example url https://everypolitician-image-proxy.herokuapp.com/http%3A%2F%2Fwww.lagtinget.ax%2Ffiles%2FAndersEriksson.jpg/0/200.jpg
